apiVersion: v1
kind: Pod
metadata:
  name: roku-client
  labels:
    app: roku-client
  annotations:
spec:
  containers:
  - name: roku-client
    image: tarasglek/roku-client
    command:
    - python
    - server.py
    - '8888'
---
kind: Service
apiVersion: v1
metadata:
  name: roku-client
spec:
  selector:
    app: roku-client
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888

